#!/bin/bash

# Generate the documentation using tfplugindocs
# remove changes to files that shouldn't change
exclude_files=()

# Check for manual changes made to any excluded files and exit
if [ "$(git status --porcelain "${exclude_files[@]}")" ]; then
  echo "Uncommitted changes were detected to the following files. These aren't autogenerated, please commit or stash these changes and try again"
  echo $(git status --porcelain "${exclude_files[@]}")
  exit 1
fi

tfplugindocs generate --provider-name "solidserver" --rendered-provider-name "SOLIDserver" --rendered-website-dir './gendoc'

# Remove the changes to files we don't autogenerate
git checkout HEAD -- "${exclude_files[@]}"
